#
# Copyright (c) 2019 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

---
language: go
sudo: required

os:
- linux
- linux-ppc64le

go_import_path: github.com/kata-containers/ksm-throttler

before_script:
  - ".ci/setup.sh"
  # go version should pass with:
  # https://github.com/kata-containers/runtime/blob/master/versions.yaml
  - ".ci/install_go.sh"
  - ".ci/static-checks.sh"

install:
  - go_packages=$(go list ./... | grep -v vendor)
  - go_files=`go list -f '{{.Dir}}/*.go' $go_packages`
  - go get -t -v $go_packages

install:
  - cd ${TRAVIS_BUILD_DIR} && make

script:
  - go env
  - cd ${TRAVIS_BUILD_DIR} && make && make check

after_success:
  - "$GOPATH/bin/goveralls -service=travis-ci -coverprofile=/tmp/cover.out"
  - bash <(curl -s https://codecov.io/bash)
