language: go
sudo: required
go:
- 1.8
- 1.9
- tip
go_import_path: github.com/kata-containers/ksm-throttler

before_script:
  - ".ci/static-checks.sh"

install:
- go_packages=$(go list ./... | grep -v vendor)
- go_files=`go list -f '{{.Dir}}/*.go' $go_packages`
- go get -t -v $go_packages

install:
  - cd ${TRAVIS_BUILD_DIR} && make

script:
  - go env
  - cd ${TRAVIS_BUILD_DIR} && make && make check

after_success:
- "$GOPATH/bin/goveralls -service=travis-ci -coverprofile=/tmp/cover.out"
- bash <(curl -s https://codecov.io/bash)
